version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    container_name: spanner-emulator
    ports:
      - "9010:9010"
      - "9020:9020"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9020/v1/projects"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: bitnami/postgresql:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=robogo_testuser
      - POSTGRESQL_PASSWORD=robogo_testpass
      - POSTGRESQL_DATABASE=robogo_testdb
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - ./data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=robogo_testpass psql -U robogo_testuser -d robogo_testdb -c 'SELECT 1;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=robogo_user
      - RABBITMQ_DEFAULT_PASS=robogo_pass
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data: 